# Generated by Django 4.0.2 on 2022-02-27 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('essential', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='total',
        ),
    ]
