# Generated by Django 4.0.2 on 2022-02-27 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('essential', '0002_remove_income_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='net_income',
        ),
    ]
