# Generated by Django 4.0.2 on 2022-05-06 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('essential', '0004_expense_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='method_of_payment',
            new_name='mop',
        ),
    ]
