# Generated by Django 4.0.2 on 2022-05-07 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('essential', '0005_rename_method_of_payment_expense_mop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='payment',
        ),
    ]
